print("welcome to TN travels")
a=input("enter your name: ")
b=input("enter depature point: ")
c=input("enter the destination: ")
d=int(input("enter the kilometer: "))
e=int(input("enter the mobile number: "))
print("chose the comfortability ")
print("1.premium")
print("2.deluxe")
print("3.ultra deluxe")
f=int(input())
def premium():
    g =(d*10)
    print("name ",end=" ")
    print(a)
    print("mobile ",end=" ")
    print(e)
    print("depat ",end=" ")
    print(b)
    print("dest ",end=" ")
    print(c)
    print("coach ",end=" ")
    print("premium")
    print("total amount ",end=" ")
    print(g)
def deluxe():
    g=(d*25)
    print("name ",end=" ")
    print(a)
    print("mobile ",end=" ")
    print(e)
    print("depat ",end=" ")
    print(b)
    print("dest ",end=" ")
    print(c)
    print("coach ",end=" ")
    print("deluxe")
    print("total amount ",end=" ")
    print(g)
def ultra():
    g=(d*30)
    print("name ",end=" ")
    print(a)
    print("mobile ",end=" ")
    print(e)
    print("depat ",end=" ")
    print(b)
    print("dest ",end=" ")
    print(c)
    print("coach ",end=" ")
    print("ul.deluxe")
    print("total amount ",end=" ")
    print(g)
def choise():
    if(f==1):
        premium()
    if(f==2):
        deluxe()
    if(f==3):
        ultra()
choise()
